# Generated by Django 3.2.8 on 2023-01-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('HeightsMap', models.TextField()),
                ('TriPolArray', models.TextField()),
                ('Color', models.TextField()),
            ],
            options={
                'db_table': 'canvas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('role', models.TextField()),
                ('moderator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('range', models.FloatField()),
                ('smooth', models.BooleanField()),
                ('mult', models.IntegerField()),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('size', models.IntegerField()),
                ('canvas_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.canvas')),
            ],
            options={
                'db_table': 'params',
            },
        ),
        migrations.AddField(
            model_name='canvas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.user'),
        ),
    ]
